### ISSUE TITLE
`realpath` missing in macOS 12 and earlier

### ISSUE THREAD

**Issue by csoneson** [grimbough/bioc-actions#14]
👋🏻 I just ran into an [issue](https://github.com/csoneson/treeclimbR/actions/runs/8293757267/job/22800219932) with the `setup-bioc` action (after the recent modification to use `get-r-version.sh` instead of `get-r-version.R`) on the `macos-latest` GitHub Actions runner (running macOS 12), where the `realpath` command can not be found. From what I understand (e.g. [here](https://apple.stackexchange.com/questions/450035/is-the-unix-realpath-command-distributed-with-macos-ventura)), it seems that this was indeed added in macOS 13 (which would explain why the [biocActionsExamples](https://github.com/grimbough/biocActionsExamples/actions/runs/8297157452/job/22707655825) passes this step). I could work around it by installing `coreutils` in `macos-latest` (or I guess I could have changed to `macos-13`), but I just wanted to bring it up as it may affect others.

**Comment by grimbough** [comment]
Annoying! Thanks for the report. 

I made the change to using bash because GitHub seems to have removed R from the base `macos-13` runner breaking the old version that ran `Rscript`. The I updated the test to use that runner and missed the new problem it introduced. Maybe there's something more portable than `realpath`? 

I'll have a look and apply a fix ASAP.

**Comment by grimbough** [comment]
I think this is now fixed by adding a fallpack option if the built in tool doesn't exist, along with a separate issue that was causing the `macos-13` pipelines to fail (https://github.com/r-lib/actions/issues/810)

**Comment by csoneson** [comment]
Awesome, thanks @grimbough!
